import React, { useState, useEffect } from 'react';
import { 
  IconCalendarStats, IconPencilCheck, IconBulb, 
  IconArrowUpRight, IconArrowDownRight, IconNotes,
  IconBrain
} from '@tabler/icons-react';
import { BASE_URL } from '../api';

function WeeklyReportCard({ role }) {
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(false);

  useEffect(() => {
    const fetchReport = async () => {
      try {
        setError(false);
        const token = localStorage.getItem('token');
        const response = await fetch(`${BASE_URL}/analytics/weekly-report`, {
          headers: { 'Authorization': `Bearer ${token}` }
        });
        if (response.ok) {
          const result = await response.json();
          setData(result);
        } else {
          setError(true);
        }
      } catch (err) {
        console.error('Failed to fetch weekly report', err);
        setError(true);
      } finally {
        setLoading(false);
      }
    };
    fetchReport();
  }, []);

  if (loading) return (
    <div className="weekly-report-card loading">
       <div className="shimmer-wrapper">
         <div className="shimmer"></div>
       </div>
       <p>Analyzing weekly activity...</p>
    </div>
  );

  if (error) return (
    <div className="weekly-report-card error">
       <div className="error-content">
         <IconBulb size={24} color="#94a3b8" />
         <p>Weekly insights temporarily unavailable</p>
         <button onClick={() => window.location.reload()} className="retry-btn">Retry</button>
       </div>
    </div>
  );

  // Consider it "empty" if all major metrics are 0
  const isEmpty = data && 
    (data.attendance?.overall === 0 && 
     data.notes?.frequency === 0 && 
     data.quiz?.averageScore === 0);

  if (isEmpty) return (
    <div className="weekly-report-card empty">
       <div className="empty-state-content">
          <div className="empty-icon-ring">
            <IconBulb size={32} />
          </div>
          <h3>Your Weekly Insight Awaits</h3>
          {role === 'student' && (
            <>
              <p>Complete quizzes, attend classes, or generate notes to see your learning trends here.</p>
              <button className="start-btn" onClick={() => window.location.href = '/notes-ai'}>
                Start Now
              </button>
            </>
          )}
       </div>
    </div>
  );

  if (!data) return null;

  return (
    <div className="weekly-report-card">
      <div className="report-header">
        <div className="report-title-grp">
          <IconBulb className="insight-icon" size={20} />
          <h3>Weekly Class Learning Report</h3>
        </div>
        <span className="week-label">Last 7 Days</span>
      </div>

      <div className="report-stats-grid">
        <div className="report-stat-item">
          <div className="stat-label">
            <IconCalendarStats size={16} /> 
            <span>Attendance</span>
          </div>
          <div className="stat-main">
            <h4>{(data.attendance?.overall || 0).toFixed(0)}%</h4>
            <div className={`trend ${(data.attendance?.overall || 0) > 75 ? 'up' : 'down'}`}>
              {(data.attendance?.overall || 0) > 75 ? <IconArrowUpRight size={14}/> : <IconArrowDownRight size={14}/>}
              <span>{(data.attendance?.overall || 0) > 75 ? 'Good' : 'Needs Focus'}</span>
            </div>
          </div>
        </div>

        <div className="report-stat-item">
          <div className="stat-label">
            <IconNotes size={16} /> 
            <span>Notes Activity</span>
          </div>
          <div className="stat-main">
            <h4>{data.notes?.frequency || 0}</h4>
            <div className={`status-badge ${(data.notes?.status || 'Normal').toLowerCase()}`}>
              {data.notes?.status || 'Normal'}
            </div>
          </div>
        </div>

        <div className="report-stat-item">
          <div className="stat-label">
            <IconPencilCheck size={16} /> 
            <span>Quiz Performance</span>
          </div>
          <div className="stat-main">
            <h4>{(data.quiz?.averageScore || 0).toFixed(0)}%</h4>
            <div className="sub-text">{(data.quiz?.totalAttempts || 0)} Attempts</div>
          </div>
        </div>
      </div>

      <div className="report-footer">
        <div style={{ display: 'flex', flexDirection: 'column', gap: '4px' }}>
          <p>This report is generated by the AI Analytics Engine based on clustered data.</p>
          <p style={{ color: '#6366f1', fontWeight: '600', fontStyle: 'normal' }}>Your performance tracker is also ready for deep analysis.</p>
        </div>
        <button 
          className="analyze-intelligence-btn" 
          onClick={() => window.location.href='/analytics'}
          style={{
            display: 'flex',
            alignItems: 'center',
            gap: '8px',
            padding: '10px 20px',
            background: 'linear-gradient(135deg, #6366f1 0%, #4f46e5 100%)',
            color: 'white',
            border: 'none',
            borderRadius: '12px',
            fontWeight: '600',
            fontSize: '13px',
            cursor: 'pointer',
            transition: 'all 0.2s',
            boxShadow: '0 4px 12px rgba(99, 102, 241, 0.2)'
          }}
          onMouseEnter={(e) => {
            e.currentTarget.style.transform = 'translateY(-2px)';
            e.currentTarget.style.boxShadow = '0 6px 16px rgba(99, 102, 241, 0.3)';
          }}
          onMouseLeave={(e) => {
            e.currentTarget.style.transform = 'none';
            e.currentTarget.style.boxShadow = '0 4px 12px rgba(99, 102, 241, 0.2)';
          }}
        >
          <IconBrain size={16} />
          Analyze with Intelligence
        </button>
      </div>

      <style dangerouslySetInnerHTML={{ __html: `
        .weekly-report-card {
          background: white;
          border-radius: 24px;
          padding: 32px;
          border: 1px solid var(--border-color);
          box-shadow: var(--shadow-sm);
          grid-column: span 3;
          animation: slideUp 0.4s ease-out;
          min-height: 250px;
          display: flex;
          flex-direction: column;
        }

        /* Loading State & Shimmer */
        .weekly-report-card.loading {
          justify-content: center;
          align-items: center;
          color: var(--text-secondary);
          gap: 12px;
        }
        .shimmer-wrapper {
          width: 100%;
          height: 150px;
          background: #f1f5f9;
          border-radius: 12px;
          overflow: hidden;
          position: relative;
        }
        .shimmer {
          width: 50%;
          height: 100%;
          background: linear-gradient(90deg, transparent, rgba(255,255,255,0.6), transparent);
          position: absolute;
          animation: shimmerShift 1.5s infinite;
        }
        @keyframes shimmerShift {
          0% { transform: translateX(-100%); }
          100% { transform: translateX(200%); }
        }

        /* Empty & Error States */
        .weekly-report-card.empty, .weekly-report-card.error {
          justify-content: center;
          align-items: center;
          text-align: center;
          background: linear-gradient(145deg, #ffffff, #f8fafc);
        }
        .empty-state-content, .error-content {
          max-width: 400px;
          display: flex;
          flex-direction: column;
          align-items: center;
          gap: 16px;
        }
        .empty-icon-ring {
          width: 64px;
          height: 64px;
          border-radius: 50%;
          background: #fef3c7;
          color: #d97706;
          display: flex;
          align-items: center;
          justify-content: center;
          margin-bottom: 8px;
        }
        .empty-state-content h3 {
          font-size: 20px;
          font-weight: 700;
          color: var(--text-dark);
          margin: 0;
        }
        .empty-state-content p, .error-content p {
          font-size: 14px;
          color: var(--text-secondary);
          line-height: 1.6;
          margin: 0;
        }

        .start-btn, .retry-btn {
          margin-top: 8px;
          padding: 10px 24px;
          border-radius: 12px;
          font-weight: 600;
          font-size: 14px;
          cursor: pointer;
          transition: all 0.2s;
        }
        .start-btn {
          background: var(--primary);
          color: white;
          border: none;
        }
        .start-btn:hover { background: var(--primary-hover); transform: translateY(-2px); }
        .retry-btn {
          background: white;
          border: 1px solid var(--border-color);
          color: var(--text-dark);
        }

        .report-header {
          display: flex;
          justify-content: space-between;
          align-items: center;
          margin-bottom: 24px;
        }
        .report-title-grp {
          display: flex;
          align-items: center;
          gap: 12px;
        }
        .insight-icon {
          color: #f59e0b;
        }
        .week-label {
          font-size: 12px;
          font-weight: 600;
          color: var(--text-secondary);
          background: #f1f5f9;
          padding: 4px 12px;
          border-radius: 20px;
        }
        .report-stats-grid {
          display: grid;
          grid-template-columns: repeat(3, 1fr);
          gap: 24px;
          margin-bottom: 24px;
        }
        .report-stat-item {
          padding: 16px;
          background: #f8fafc;
          border-radius: 12px;
          border: 1px solid #f1f5f9;
        }
        .stat-label {
          display: flex;
          align-items: center;
          gap: 8px;
          color: var(--text-secondary);
          font-size: 13px;
          font-weight: 600;
          margin-bottom: 12px;
        }
        .stat-main {
          display: flex;
          align-items: baseline;
          gap: 8px;
        }
        .stat-main h4 {
          font-size: 24px;
          font-weight: 700;
          color: var(--text-dark);
          margin: 0;
        }
        .trend {
          display: flex;
          align-items: center;
          gap: 2px;
          font-size: 12px;
          font-weight: 600;
        }
        .trend.up { color: #10b981; }
        .trend.down { color: #f43f5e; }
        .status-badge {
          font-size: 11px;
          font-weight: 700;
          padding: 2px 8px;
          border-radius: 4px;
          text-transform: uppercase;
        }
        .status-badge.high { background: #dcfce7; color: #15803d; }
        .status-badge.moderate { background: #fef9c3; color: #854d0e; }
        .status-badge.low { background: #fee2e2; color: #b91c1c; }
        .sub-text {
          font-size: 11px;
          color: var(--text-secondary);
          font-weight: 500;
        }
        .report-footer {
          margin-top: auto;
          display: flex;
          justify-content: space-between;
          align-items: center;
          padding-top: 16px;
          border-top: 1px dashed var(--border-color);
        }
        .report-footer p {
          font-size: 12px;
          color: var(--text-secondary);
          margin: 0;
          font-style: italic;
        }
        .view-full-btn {
          border: none;
          background: none;
          color: var(--primary);
          font-weight: 600;
          font-size: 13px;
          cursor: pointer;
        }
        .view-full-btn:hover { text-decoration: underline; }
      `}} />
    </div>
  );
}

export default WeeklyReportCard;
